// const stringInput = document.getElementById("string-input")
// console.log(stringInput)
const transformBtn = document.getElementById("transform-btn");
transformBtn.addEventListener("click", unicodeToPua);
const unTransformBtn = document.getElementById("untransform-btn");
unTransformBtn.addEventListener("click", puaToUnicode);

function unicodeToPua() {
  const inputElt = document.getElementById("string-input");
  let inputString = inputElt.value;
  const outputElt = document.getElementById("string-output");
  const simpleMode = document.getElementById("simple-mode");
  let outputString;
  rules.forEach(function (rule) {
    // console.log(rule.unicode);
    if (simpleMode.checked && rule.length <= 1) {
      return;
    }
    inputString = inputString.replace(new RegExp(rule.unicode, "g"), rule.pua);
  });
  outputElt.value = inputString;
  // console.log(outputElt)
}

function puaToUnicode() {
  const inputElt = document.getElementById("string-input");
  const outputElt = document.getElementById("string-output");
  let outputString = outputElt.value;

  rules.forEach(function (rule) {
    outputString = outputString.replace(
      new RegExp(rule.pua, "g"),
      rule.unicode
    );
  });
  inputElt.value = outputString;
}

const rulesTest = [
  {
    pua: "哈",
    unicode: "o̍",
  },
  {
    pua: "嘿",
    unicode: "ī",
  },
];

const rules = [
  {
    pua: "",
    編碼: "E000",
    unicode: "A̍",
    unicode編碼: "41",
    length: 2,
  },
  {
    pua: "",
    編碼: "E001",
    unicode: "a̍",
    unicode編碼: "61",
    length: 2,
  },
  {
    pua: "",
    編碼: "E002",
    unicode: "E̍",
    unicode編碼: "45",
    length: 2,
  },
  {
    pua: "",
    編碼: "E003",
    unicode: "e̍",
    unicode編碼: "65",
    length: 2,
  },
  {
    pua: "",
    編碼: "E006",
    unicode: "I̍",
    unicode編碼: "49",
    length: 2,
  },
  {
    pua: "",
    編碼: "E007",
    unicode: "i̍",
    unicode編碼: "69",
    length: 2,
  },
  {
    pua: "",
    編碼: "E00A",
    unicode: "M̀",
    unicode編碼: "4D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E00B",
    unicode: "m̀",
    unicode編碼: "6D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E00C",
    unicode: "M̂",
    unicode編碼: "4D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E00D",
    unicode: "m̂",
    unicode編碼: "6D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E00E",
    unicode: "M̄",
    unicode編碼: "4D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E00F",
    unicode: "m̄",
    unicode編碼: "6D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E010",
    unicode: "M̍",
    unicode編碼: "4D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E011",
    unicode: "m̍",
    unicode編碼: "6D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E014",
    unicode: "N̂",
    unicode編碼: "4E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E015",
    unicode: "n̂",
    unicode編碼: "6E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E016",
    unicode: "N̄",
    unicode編碼: "4E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E017",
    unicode: "n̄",
    unicode編碼: "6E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E018",
    unicode: "N̍",
    unicode編碼: "4E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E019",
    unicode: "n̍",
    unicode編碼: "6E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E01C",
    unicode: "O̍",
    unicode編碼: "4F",
    length: 2,
  },
  {
    pua: "",
    編碼: "E01D",
    unicode: "o̍",
    unicode編碼: "6F",
    length: 2,
  },
  {
    pua: "",
    編碼: "E020",
    unicode: "O͘",
    unicode編碼: "4F",
    length: 2,
  },
  {
    pua: "",
    編碼: "E021",
    unicode: "o͘",
    unicode編碼: "6F",
    length: 2,
  },
  {
    pua: "",
    編碼: "E022",
    unicode: "Ó͘",
    unicode編碼: "D3",
    length: 2,
  },
  {
    pua: "",
    編碼: "E023",
    unicode: "ó͘",
    unicode編碼: "F3",
    length: 2,
  },
  {
    pua: "",
    編碼: "E024",
    unicode: "Ò͘",
    unicode編碼: "D2",
    length: 2,
  },
  {
    pua: "",
    編碼: "E025",
    unicode: "ò͘",
    unicode編碼: "F2",
    length: 2,
  },
  {
    pua: "",
    編碼: "E026",
    unicode: "Ô͘",
    unicode編碼: "D4",
    length: 2,
  },
  {
    pua: "",
    編碼: "E027",
    unicode: "ô͘",
    unicode編碼: "F4",
    length: 2,
  },
  {
    pua: "",
    編碼: "E028",
    unicode: "Ō͘",
    unicode編碼: "14C",
    length: 2,
  },
  {
    pua: "",
    編碼: "E029",
    unicode: "ō͘",
    unicode編碼: "14D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E02A",
    unicode: "O̍͘",
    unicode編碼: "4F",
    length: 3,
  },
  {
    pua: "",
    編碼: "E02B",
    unicode: "o̍͘",
    unicode編碼: "6F",
    length: 3,
  },
  {
    pua: "",
    編碼: "E030",
    unicode: "U̍",
    unicode編碼: "55",
    length: 2,
  },
  {
    pua: "",
    編碼: "E031",
    unicode: "u̍",
    unicode編碼: "75",
    length: 2,
  },
  {
    pua: "",
    編碼: "E04C",
    unicode: "Ŏ͘",
    unicode編碼: "14E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E04D",
    unicode: "ŏ͘",
    unicode編碼: "14F",
    length: 2,
  },
  {
    pua: "",
    編碼: "E086",
    unicode: "M̆",
    unicode編碼: "4D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E087",
    unicode: "m̆",
    unicode編碼: "6D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E088",
    unicode: "N̆",
    unicode編碼: "4E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E089",
    unicode: "n̆",
    unicode編碼: "6E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E094",
    unicode: "E̋",
    unicode編碼: "45",
    length: 2,
  },
  {
    pua: "",
    編碼: "E095",
    unicode: "e̋",
    unicode編碼: "65",
    length: 2,
  },
  {
    pua: "",
    編碼: "E096",
    unicode: "I̋",
    unicode編碼: "49",
    length: 2,
  },
  {
    pua: "",
    編碼: "E097",
    unicode: "i̋",
    unicode編碼: "69",
    length: 2,
  },
  {
    pua: "",
    編碼: "E098",
    unicode: "M̋",
    unicode編碼: "4D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E099",
    unicode: "m̋",
    unicode編碼: "6D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E09A",
    unicode: "N̋",
    unicode編碼: "4E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E09B",
    unicode: "n̋",
    unicode編碼: "6E",
    length: 2,
  },
  {
    pua: "",
    編碼: "E09C",
    unicode: "Ő",
    unicode編碼: "150",
    length: 1,
  },
  {
    pua: "",
    編碼: "E09D",
    unicode: "ő",
    unicode編碼: "151",
    length: 1,
  },
  {
    pua: "",
    編碼: "E09E",
    unicode: "Ű",
    unicode編碼: "170",
    length: 1,
  },
  {
    pua: "",
    編碼: "E09F",
    unicode: "ű",
    unicode編碼: "171",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A0",
    unicode: "Ā",
    unicode編碼: "100",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A1",
    unicode: "Á",
    unicode編碼: "C1",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A2",
    unicode: "Ǎ",
    unicode編碼: "1CD",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A3",
    unicode: "À",
    unicode編碼: "C0",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A4",
    unicode: "Â",
    unicode編碼: "C2",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A5",
    unicode: "Ă",
    unicode編碼: "102",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A7",
    unicode: "Ē",
    unicode編碼: "112",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A8",
    unicode: "É",
    unicode編碼: "C9",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0A9",
    unicode: "Ě",
    unicode編碼: "11A",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0AA",
    unicode: "È",
    unicode編碼: "C8",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0AB",
    unicode: "Ê",
    unicode編碼: "CA",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0AC",
    unicode: "Ĕ",
    unicode編碼: "114",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0AE",
    unicode: "Ī",
    unicode編碼: "12A",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0AF",
    unicode: "Í",
    unicode編碼: "CD",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0B0",
    unicode: "Ǐ",
    unicode編碼: "1CF",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0B1",
    unicode: "Ì",
    unicode編碼: "CC",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0B2",
    unicode: "Î",
    unicode編碼: "CE",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0B3",
    unicode: "Ĭ",
    unicode編碼: "12C",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0B6",
    unicode: "Ḿ",
    unicode編碼: "1E3E",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0B7",
    unicode: "M̌",
    unicode編碼: "4D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E0B9",
    unicode: "Ń",
    unicode編碼: "143",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0BA",
    unicode: "Ň",
    unicode編碼: "147",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0BB",
    unicode: "Ǹ",
    unicode編碼: "1F8",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0BD",
    unicode: "Ō",
    unicode編碼: "14C",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0BE",
    unicode: "Ó",
    unicode編碼: "D3",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0BF",
    unicode: "Ǒ",
    unicode編碼: "1D1",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0C0",
    unicode: "Ò",
    unicode編碼: "D2",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0C1",
    unicode: "Ô",
    unicode編碼: "D4",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0C2",
    unicode: "Ŏ",
    unicode編碼: "14E",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0C5",
    unicode: "Ū",
    unicode編碼: "16A",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0C6",
    unicode: "Ú",
    unicode編碼: "DA",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0C7",
    unicode: "Ǔ",
    unicode編碼: "1D3",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0C8",
    unicode: "Ù",
    unicode編碼: "D9",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0C9",
    unicode: "Û",
    unicode編碼: "DB",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0CA",
    unicode: "Ŭ",
    unicode編碼: "16C",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0CC",
    unicode: "ā",
    unicode編碼: "101",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0CD",
    unicode: "á",
    unicode編碼: "E1",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0CE",
    unicode: "ǎ",
    unicode編碼: "1CE",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0CF",
    unicode: "à",
    unicode編碼: "E0",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0D0",
    unicode: "â",
    unicode編碼: "E2",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0D1",
    unicode: "ă",
    unicode編碼: "103",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0D3",
    unicode: "ē",
    unicode編碼: "113",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0D4",
    unicode: "é",
    unicode編碼: "E9",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0D5",
    unicode: "ě",
    unicode編碼: "11B",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0D6",
    unicode: "è",
    unicode編碼: "E8",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0D7",
    unicode: "ê",
    unicode編碼: "EA",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0D8",
    unicode: "ĕ",
    unicode編碼: "115",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0DA",
    unicode: "ī",
    unicode編碼: "12B",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0DB",
    unicode: "í",
    unicode編碼: "ED",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0DC",
    unicode: "ǐ",
    unicode編碼: "1D0",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0DD",
    unicode: "ì",
    unicode編碼: "EC",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0DE",
    unicode: "î",
    unicode編碼: "EE",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0DF",
    unicode: "ĭ",
    unicode編碼: "12D",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0E2",
    unicode: "ḿ",
    unicode編碼: "1E3F",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0E3",
    unicode: "m̌",
    unicode編碼: "6D",
    length: 2,
  },
  {
    pua: "",
    編碼: "E0E6",
    unicode: "ń",
    unicode編碼: "144",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0E7",
    unicode: "ň",
    unicode編碼: "148",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0E8",
    unicode: "ǹ",
    unicode編碼: "1F9",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0EC",
    unicode: "ō",
    unicode編碼: "14D",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0ED",
    unicode: "ó",
    unicode編碼: "F3",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0EE",
    unicode: "ǒ",
    unicode編碼: "1D2",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0EF",
    unicode: "ò",
    unicode編碼: "F2",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0F0",
    unicode: "ô",
    unicode編碼: "F4",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0F1",
    unicode: "ŏ",
    unicode編碼: "14F",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0F4",
    unicode: "ū",
    unicode編碼: "16B",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0F5",
    unicode: "ú",
    unicode編碼: "FA",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0F6",
    unicode: "ǔ",
    unicode編碼: "1D4",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0F7",
    unicode: "ù",
    unicode編碼: "F9",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0F8",
    unicode: "û",
    unicode編碼: "FB",
    length: 1,
  },
  {
    pua: "",
    編碼: "E0F9",
    unicode: "ŭ",
    unicode編碼: "16D",
    length: 1,
  },
];
